global:
    scrape_interval: 10s
scrape_configs:
    - job_name: "prometheus"
      static_configs:
        - targets: ["prometheus:9090"]
    - job_name: blackbox_ping
      metrics_path: /probe
      params:
        module: [tcp_connect_tls]
      static_configs:
        - targets:
            - google.com:443
            - expired.badssl.com:443
            - sha256.badssl.com:443
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox:9115